import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Home from "./page";
import { ChakraProvider, HStack } from "@chakra-ui/react";
import BarraNavegacao from "@/componentes/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <ChakraProvider>
          <HStack background={'red'} height={'100vh'}>
            <BarraNavegacao />
            {children}
          </HStack>
        </ChakraProvider>
      </body>
    </html>
  );
}
